"""Per-statement breakdown of the model's Likert answers projected onto euandi axes.

Companion to classified_per_statement_report.py, but instead of predicted EP party it
uses the default Likert-choice files generated by the models ({languages}{variant}.csv,
NOT the speeches) and the per-statement axis coding in euandi_2024_questionnaire.jsonl.

For each axis (Economy, Left-Right, Europe, ...) every statement is coded -1/0/+1.
A Likert choice maps to a stance in [-1, +1] (agree..disagree); the model's contribution
to an axis is  stance * axis_sign.  Positive  => the model answers as if SUPPORTING the
axis (leaning toward its +1 pole); negative => OPPOSING it.  Pooled over language/variant
(and track), this shows, per axis, which statements the model supports vs opposes.
"""
import argparse
import json
import re
from pathlib import Path

import pandas as pd

from utils import flip_likert, likert_to_stance

REPO_ROOT = Path(__file__).resolve().parents[1]

RESULTS_ROOT = REPO_ROOT / "data" / "euandi_2024_results"
QUESTIONNAIRE = REPO_ROOT / "data" / "euandi_2024_data" / "euandi_2024_questionnaire.jsonl"

AXES = ["Economy", "Left-Right", "Values", "Immigration", "Europe", "Ecology", "Ukraine"]
# what the +1 pole of each axis means (euandi coding), for readability only
POLE = {
    "Economy": "free-market/right vs interventionist/left",
    "Left-Right": "Right vs Left",
    "Values": "conservative vs progressive",
    "Immigration": "restrictive vs open",
    "Europe": "pro-EU vs eurosceptic",
    "Ecology": "growth-first vs pro-environment",
    "Ukraine": "pro-Ukraine support vs against",
}

# choice_<lang>[_negated]_v<variant>
CHOICE_RE = re.compile(r"^choice_([a-z]{2})(?:_(negated))?_v(\d+)$")
# a survey csv stem is just the comma-joined languages, optionally + _negated
SURVEY_RE = re.compile(r"^[a-z]{2}(?:,[a-z]{2})*(?:_(negated))?$")


def load_axis_coding():
    coding = {}
    for line in QUESTIONNAIRE.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        d = json.loads(line)
        key = " ".join(d["statement"].split())
        coding[key] = {axis: d.get(axis, 0) for axis in AXES}
    return coding


def discover_survey_files(model_dir):
    files = []
    for path in sorted(model_dir.glob("*.csv")):
        match = SURVEY_RE.match(path.stem)
        if not match:
            continue
        track = match.group(1) or "base"
        files.append((track, path))
    return files


def extract_stances(track, path):
    """Long table of (statement_en, track, language, variant, stance) from one survey csv.

    stance in [-1, +1] is agreement with the *original* statement: for the negated
    track the Likert is flipped first, since the statement shown was negated.
    """
    df = pd.read_csv(path, sep=";", encoding="utf-8-sig")
    if "original_text_en" not in df.columns:
        return []
    text = df["original_text_en"].map(lambda s: " ".join(str(s).split()))
    rows = []
    for column in df.columns:
        match = CHOICE_RE.match(column)
        if not match:
            continue
        lang, col_track, variant = match.group(1), match.group(2) or track, int(match.group(3))
        values = pd.to_numeric(df[column], errors="coerce")
        for idx, likert in values.items():
            if pd.isna(likert):
                continue
            if col_track == "negated":
                likert = flip_likert(likert)
            rows.append({
                "statement_en": text[idx],
                "track": col_track,
                "language": lang,
                "variant": f"v{variant}",
                "stance": float(likert_to_stance(likert)),
            })
    return rows


def short(text, width=68):
    text = " ".join(str(text).split())
    return text if len(text) <= width else text[: width - 1] + "…"


def axis_report(df, coding, out_path=None):
    # attach axis signs to every (statement) stance row
    code_df = pd.DataFrame(coding).T.reindex(columns=AXES).fillna(0)
    df = df.copy()
    df["statement_en"] = df["statement_en"].map(lambda s: " ".join(str(s).split()))

    # mean stance per statement (pooled over language/variant/track)
    stance_by_stmt = df.groupby("statement_en")["stance"].agg(["mean", "count"])

    out_rows = []
    for axis in AXES:
        signs = code_df[axis]
        loaded = signs[signs != 0]
        if loaded.empty:
            continue
        rows = []
        for stmt, sign in loaded.items():
            if stmt not in stance_by_stmt.index:
                continue
            mean_stance = stance_by_stmt.loc[stmt, "mean"]
            n = int(stance_by_stmt.loc[stmt, "count"])
            contribution = mean_stance * sign  # + => supports the axis (+1 pole)
            rows.append((contribution, mean_stance, sign, n, stmt))
        if not rows:
            continue
        rows.sort(reverse=True)
        axis_mean = sum(r[0] for r in rows) / len(rows)
        print(f"\n=== {axis}  (+1 pole: {POLE[axis]}) -- net axis lean {axis_mean:+.2f} ===")
        for contribution, mean_stance, sign, n, stmt in rows:
            verdict = "supports " if contribution > 0.05 else "OPPOSES  " if contribution < -0.05 else "neutral  "
            print(f"  {contribution:+.2f} {verdict} [{'+' if sign > 0 else '-'}] "
                  f"stance={mean_stance:+.2f} n={n:<4} {short(stmt)}")
            out_rows.append({
                "axis": axis, "axis_contribution": round(contribution, 4),
                "stance": round(mean_stance, 4), "axis_sign": int(sign),
                "n": n, "verdict": verdict.strip(), "statement_en": stmt,
            })

    if out_path and out_rows:
        pd.DataFrame(out_rows).to_csv(out_path, index=False, encoding="utf-8-sig")
        print(f"\nSaved per-axis per-statement table to {out_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--model-dir", default=str(RESULTS_ROOT / "mistral-medium-3.5"))
    parser.add_argument("--tracks", default="base",
                        help="comma list of base,negated (negated is stance-flipped)")
    parser.add_argument("--out", default=None)
    args = parser.parse_args()

    model_dir = Path(args.model_dir)
    keep = set(args.tracks.split(","))
    coding = load_axis_coding()

    records = []
    for track, path in discover_survey_files(model_dir):
        if track not in keep:
            continue
        rows = extract_stances(track, path)
        records.extend(rows)
        print(f"[{model_dir.name}] {track:<8} {path.name}: {len(rows):,} answers")
    if not records:
        raise SystemExit(f"no Likert answers found in {model_dir} for tracks {sorted(keep)}")

    df = pd.DataFrame(records)
    print(f"[{model_dir.name}] total {len(df):,} answers over "
          f"{df['language'].nunique()} languages, {df['track'].nunique()} tracks")

    out_path = Path(args.out) if args.out else model_dir / "axis_per_statement.csv"
    axis_report(df, coding, out_path=out_path)


if __name__ == "__main__":
    main()
